# Generated by Django 5.0.14 on 2026-09-04 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('alpha_acid', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Альфа-кислота, %')),
                ('aroma', models.TextField(blank=True, verbose_name='Аромат')),
            ],
            options={
                'verbose_name': 'Хмель',
                'verbose_name_plural': 'Хмель',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('style', models.CharField(blank=True, max_length=200, verbose_name='Стиль')),
                ('abv', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Крепость, %')),
                ('ibu', models.PositiveIntegerField(blank=True, null=True, verbose_name='IBU')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('hops', models.ManyToManyField(blank=True, related_name='beers', to='brewery.hop', verbose_name='Хмель')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beers', to='brewery.vendor', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Пиво',
                'verbose_name_plural': 'Пиво',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Оценка (1-10)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='brewery.beer', verbose_name='Пиво')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemM2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('beers', models.ManyToManyField(blank=True, related_name='systems', to='brewery.beer', verbose_name='Пиво')),
            ],
            options={
                'verbose_name': 'Система',
                'verbose_name_plural': 'Системы',
                'ordering': ['name'],
            },
        ),
    ]
