# Generated by Django 5.0.14 on 2026-09-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemM2M',
        ),
    ]
