# Generated by Django 5.0.14 on 2026-09-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0003_load_top_50_hops'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='gost',
            field=models.CharField(blank=True, max_length=100, verbose_name='ГОСТ'),
        ),
        migrations.AddField(
            model_name='beer',
            name='og',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='OG'),
        ),
        migrations.AddField(
            model_name='beer',
            name='value_deal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Цена/качество'),
        ),
        migrations.AddField(
            model_name='hop',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='hop',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
