# Generated by Django 5.0.14 on 2026-09-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0005_update_hops_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='beers/', verbose_name='Картинка'),
        ),
    ]
